# -*- coding: utf-8 -*-
"""iris_knn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pKAJwqFw5TeLtzTLkx6UUdF8RHHYDujK
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (confusion_matrix, classification_report, accuracy_score, f1_score,)

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

iris = load_iris()
X = iris.data
y = iris.target
feature_names = iris.feature_names
target_names = iris.target_names

df = pd.DataFrame(X, columns=feature_names)
df["species"] = pd.Categorical.from_codes(y, target_names)

print("Dataset shape:", df.shape)
print(df["species"].value_counts())
print(df.describe())

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=RANDOM_STATE, shuffle=True, stratify=y,)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

k_range = range(1, 31)
error_rates = []
for k in k_range:
    knn_k = KNeighborsClassifier(n_neighbors=k)
    knn_k.fit(X_train_scaled, y_train)
    preds_k = knn_k.predict(X_test_scaled)
    error_rates.append(1 - accuracy_score(y_test, preds_k))

plt.plot(k_range, error_rates, marker="o", linestyle="--")
plt.title("Error Rate vs K"); plt.xlabel("K"); plt.ylabel("Error Rate")
plt.show()

best_k = k_range[int(np.argmin(error_rates))]
print(f"Best K: {best_k}")

model = KNeighborsClassifier(n_neighbors=best_k)
model.fit(X_train_scaled, y_train)
predictions = model.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, predictions))
print("Macro F1:", f1_score(y_test, predictions, average="macro"))
print(classification_report(y_test, predictions, target_names=target_names))

cm = confusion_matrix(y_test, predictions)
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=target_names, yticklabels=target_names)
plt.xlabel("Predicted"); plt.ylabel("Actual")
plt.show()

new_sample = np.array([[5.1, 3.5, 1.4, 0.2]])
new_pred = model.predict(scaler.transform(new_sample))
print("Prediction:", target_names[new_pred[0]])

